import type { AnnualReportSectionDefinition } from "./vyrocni-zprava-types";

function def(
  id: string,
  number: string,
  title: string,
  description: string,
  requiredFields: AnnualReportSectionDefinition["requiredFields"],
  order: number,
  opts?: { parentNumber?: string; listTitle?: string },
): AnnualReportSectionDefinition {
  return {
    id,
    number,
    title,
    description,
    requiredFields,
    order,
    parentNumber: opts?.parentNumber,
    listTitle: opts?.listTitle,
  };
}

/** Struktura kapitol podle § 7 vyhlášky č. 15/2005 Sb. – pouze definice, bez uživatelského stavu. */
export const ANNUAL_REPORT_SECTION_DEFINITIONS: AnnualReportSectionDefinition[] = [
  def(
    "01",
    "01",
    "Základní údaje o škole",
    "Identifikační a kontaktní údaje školy, charakteristika, zřizovatel, vedení a školská rada.",
    ["school.name", "school.ico", "school.redIzo", "school.address", "school.municipality", "school.region", "school.founder", "school.principalName", "school.website", "school.email", "school.schoolType"],
    1,
  ),
  def("1.1", "1.1", "Název školy", "Oficiální název školy podle zápisu ve školském rejstříku.", ["school.name"], 2, {
    parentNumber: "01",
  }),
  def(
    "1.2",
    "1.2",
    "Sídlo školy",
    "Adresa sídla školy včetně PSČ.",
    ["school.address", "school.municipality", "school.region"],
    3,
    { parentNumber: "01" },
  ),
  def(
    "1.3",
    "1.3",
    "Charakteristika školy",
    "Stručný popis zaměření, organizace a specifik školy.",
    ["section.userNotes"],
    4,
    { parentNumber: "01" },
  ),
  def("1.4", "1.4", "Zřizovatel školy", "Název a sídlo zřizovatele.", ["school.founder"], 5, { parentNumber: "01" }),
  def(
    "1.5",
    "1.5",
    "Údaje o vedení školy",
    "Jméno ředitele a případně zástupců ředitele.",
    ["school.principalName"],
    6,
    { parentNumber: "01" },
  ),
  def(
    "1.6",
    "1.6",
    "Adresa pro dálkový přístup",
    "Webová adresa školy pro vzdálený přístup k informacím.",
    ["school.website"],
    7,
    { parentNumber: "01" },
  ),
  def(
    "1.7",
    "1.7",
    "Údaje o školské radě",
    "Složení školské rady a způsob jednání.",
    ["section.userNotes"],
    8,
    { parentNumber: "01" },
  ),
  def(
    "1.8",
    "1.8",
    "Materiálně-technické podmínky",
    "Přehled budov, učeben, vybavení a významných investic.",
    ["section.userNotes"],
    9,
    { parentNumber: "01" },
  ),
  def(
    "02",
    "02",
    "Přehled oborů vzdělání, které škola vyučuje v souladu se zápisem ve školském rejstříku",
    "Výčet vzdělávacích programů a oborů vzdělání podle aktuálního zápisu.",
    ["section.userNotes"],
    10,
    { listTitle: "Obory vzdělání dle zápisu ve školském rejstříku" },
  ),
  def(
    "03",
    "03",
    "Rámcový popis personálního zabezpečení činnosti školy",
    "Přehled pracovníků školy podle věku, pohlaví, vzdělání a odborné kvalifikace.",
    ["section.userNotes"],
    11,
    { listTitle: "Personální zabezpečení školy" },
  ),
  def(
    "3.1",
    "3.1",
    "Základní údaje o pracovnících školy",
    "Celkový počet pedagogických a nepedagogických pracovníků.",
    ["section.userNotes"],
    12,
    { parentNumber: "03" },
  ),
  def(
    "3.2",
    "3.2",
    "Členění pedagogických zaměstnanců podle věku a pohlaví",
    "Věkové a genderové složení pedagogického sboru.",
    ["section.userNotes"],
    14,
    { parentNumber: "03", listTitle: "Pedagogové podle věku a pohlaví" },
  ),
  def(
    "3.3",
    "3.3",
    "Členění pedagogických zaměstnanců podle vzdělání a pohlaví",
    "Úroveň dosaženého vzdělání pedagogických pracovníků.",
    ["section.userNotes"],
    15,
    { parentNumber: "03", listTitle: "Pedagogové podle vzdělání a pohlaví" },
  ),
  def(
    "3.4",
    "3.4",
    "Členění pedagogických pracovníků podle odborné kvalifikace",
    "Přehled kvalifikace pedagogů vůči vyučovaným předmětům.",
    ["section.userNotes"],
    16,
    { parentNumber: "03", listTitle: "Odborná kvalifikace pedagogů" },
  ),
  def(
    "04",
    "04",
    "Údaje o přijímacím řízení nebo o zápisu k povinné školní docházce a následném přijetí do školy",
    "Statistiky přijatých žáků, zápisů a výsledků přijímacího řízení.",
    ["section.userNotes"],
    17,
    { listTitle: "Přijímací řízení a zápis do školy" },
  ),
  def(
    "05",
    "05",
    "Stručné vyhodnocení naplňování cílů školního vzdělávacího programu",
    "Hodnocení plnění cílů ŠVP v uplynulém školním roce.",
    ["section.userNotes"],
    18,
    { listTitle: "Plnění cílů školního vzdělávacího programu" },
  ),
  def(
    "06",
    "06",
    "Údaje o výsledcích vzdělávání žáků podle cílů stanovených vzdělávacími programy",
    "Výsledky vzdělávání, hodnocení a případné srovnání s předchozím rokem.",
    ["section.userNotes"],
    19,
    { listTitle: "Výsledky vzdělávání žáků" },
  ),
  def(
    "07",
    "07",
    "Údaje o prevenci rizikového chování a zajištění podpory žáků se speciálními vzdělávacími potřebami, nadaných, mimořádně nadaných a s nárokem na poskytování jazykové přípravy",
    "Preventivní programy, inkluze a podpora specifických skupin žáků.",
    ["section.userNotes"],
    20,
    { listTitle: "Prevence rizikového chování a podpora žáků" },
  ),
  def(
    "08",
    "08",
    "Údaje o dalším vzdělávání pedagogických pracovníků a odborném rozvoji nepedagogických pracovníků",
    "Přehled dalšího vzdělávání, kurzů a odborných aktivit zaměstnanců.",
    ["section.userNotes"],
    21,
    { listTitle: "Další vzdělávání a rozvoj pracovníků" },
  ),
  def(
    "09",
    "09",
    "Údaje o aktivitách a prezentaci školy na veřejnosti",
    "Akce, projekty, spolupráce s veřejností a mediální prezentace školy.",
    ["section.userNotes"],
    22,
    { listTitle: "Aktivity a prezentace školy" },
  ),
  def(
    "10",
    "10",
    "Údaje o výsledcích inspekční činnosti provedené Českou školní inspekcí",
    "Závěry a doporučení z posledních inspekcí ČŠI.",
    ["section.userNotes"],
    23,
    { listTitle: "Výsledky inspekční činnosti ČŠI" },
  ),
  def(
    "11",
    "11",
    "Základní údaje o hospodaření školy",
    "Stručný přehled hospodaření, rozpočtu a významných ekonomických ukazatelů.",
    ["section.userNotes"],
    24,
    { listTitle: "Hospodaření školy" },
  ),
  def(
    "12",
    "12",
    "Projekty a granty",
    "Přehled projektů, grantů a dalších programů financovaných z veřejných zdrojů.",
    ["section.userNotes"],
    25,
    { listTitle: "Projekty a granty" },
  ),
  def(
    "13",
    "13",
    "Spolupráce s rodiči a partnery",
    "Spolupráce se zákonnými zástupci, zřizovatelem a dalšími partnery školy.",
    ["section.userNotes"],
    26,
    { listTitle: "Spolupráce s rodiči a partnery" },
  ),
  def(
    "14",
    "14",
    "Závěr",
    "Celkové zhodnocení školního roku a plány do dalšího období.",
    ["section.userNotes"],
    27,
    { listTitle: "Závěr výroční zprávy" },
  ),
];
