import { describe, expect, it } from "vitest";
import type { PsychRow } from "../phmax-zs-logic";
import { applyZsFormSnapshot, buildZsFormSnapshot, type ZsFormSnapshotSetters } from "./zs-form-snapshot";

describe("zs-form-snapshot", () => {
  it("build a apply zachovají klíčová pole", () => {
    const calls: string[] = [];
    const setters = {
      setTab: (v: string) => calls.push(`tab:${v}`),
      setMode: () => {},
      setBasicType: () => {},
      setBasic1Classes: (v: number) => calls.push(`b1c:${v}`),
      setBasic1Pupils: () => {},
      setBasic2Classes: () => {},
      setBasic2Pupils: () => {},
      setIncl1Classes: () => {},
      setIncl1Pupils: () => {},
      setIncl2Classes: () => {},
      setIncl2Pupils: () => {},
      setPsychRows: () => {},
      setHealthRows: () => {},
      setExportLabel: () => {},
      setMinorityType: () => {},
      setMinority1Classes: () => {},
      setMinority1Pupils: () => {},
      setMinority2Classes: () => {},
      setMinority2Pupils: () => {},
      setGymRows: () => {},
      setMixedRows: () => {},
      setSpecial1Classes: () => {},
      setSpecial1Pupils: () => {},
      setSpecial2Classes: () => {},
      setSpecial2Pupils: () => {},
      setSpecialIIClasses: () => {},
      setSpecialIIPupils: () => {},
      setPrepClasses: () => {},
      setPrepChildren: () => {},
      setPrepSpecialClasses: () => {},
      setPrepSpecialChildren: () => {},
      setP38First: () => {},
      setP38Second: () => {},
      setP41First: () => {},
      setP41Second: () => {},
      setPhaRows: () => {},
      setPhpYear1: () => {},
      setPhpYear2: () => {},
      setPhpYear3: () => {},
      setPhpWizardStep: () => {},
      setPhpMethodMode: () => {},
      setPhpExcludedAbroad: () => {},
      setPhpExcludedForeignSchoolCz: () => {},
      setPhpExcludedIndividual: () => {},
      setPhpExcludedSchool: () => {},
      setSelectedExample: () => {},
      setWizardChoice: () => {},
      setZsWizardStep: () => {},
      setDataMode: () => {},
      setNv75Role: () => {},
      setNv75School: () => {},
      setNv75TeacherMin: () => {},
      setNv75TeacherMax: () => {},
      setMixedMethodFirstZsPupils: () => {},
      setMixedMethodFirstZsClasses: () => {},
      setMixedMethodFirstSpecialPupils: () => {},
      setMixedMethodFirstSpecialClasses: () => {},
      setMixedMethodSecondZsPupils: () => {},
      setMixedMethodSecondZsClasses: () => {},
      setMixedMethodSecondSpecialPupils: () => {},
      setMixedMethodSecondSpecialClasses: () => {},
    } as unknown as ZsFormSnapshotSetters;

    const snap = buildZsFormSnapshot({
      tab: "phmax",
      mode: "phmax_full_zs",
      basicType: "full_more_than_2",
      basic1Classes: 3,
      basic1Pupils: 0,
      basic2Classes: 0,
      basic2Pupils: 0,
      incl1Classes: 0,
      incl1Pupils: 0,
      incl2Classes: 0,
      incl2Pupils: 0,
      psychRows: [],
      healthRows: [],
      exportLabel: "test",
      minorityType: "minority1",
      minority1Classes: 0,
      minority1Pupils: 0,
      minority2Classes: 0,
      minority2Pupils: 0,
      gymRows: [],
      mixedRows: [],
      special1Classes: 0,
      special1Pupils: 0,
      special2Classes: 0,
      special2Pupils: 0,
      specialIIClasses: 0,
      specialIIPupils: 0,
      prepClasses: 0,
      prepChildren: 0,
      prepSpecialClasses: 0,
      prepSpecialChildren: 0,
      p38First: 0,
      p38Second: 0,
      p41First: 0,
      p41Second: 0,
      phaRows: [],
      phpYear1: 0,
      phpYear2: 0,
      phpYear3: 0,
      phpWizardStep: "a",
      phpMethodMode: "three_year_avg",
      phpExcludedAbroad: 0,
      phpExcludedForeignSchoolCz: 0,
      phpExcludedIndividual: 0,
      phpExcludedSchool: false,
      selectedExample: "",
      wizardChoice: "",
      zsWizardStep: 1,
      dataMode: "own",
      nv75Role: "ucitel",
      nv75School: "plavecka_skola",
      nv75TeacherMin: 22,
      nv75TeacherMax: 30,
      mixedMethodFirstZsPupils: 0,
      mixedMethodFirstZsClasses: 0,
      mixedMethodFirstSpecialPupils: 0,
      mixedMethodFirstSpecialClasses: 0,
      mixedMethodSecondZsPupils: 0,
      mixedMethodSecondZsClasses: 0,
      mixedMethodSecondSpecialPupils: 0,
      mixedMethodSecondSpecialClasses: 0,
      auditTotals: { totalPhmax: 0, totalPha: 0, totalPhp: 0, tab: "phmax" },
    });

    applyZsFormSnapshot(snap, setters, "ok", (msg) => calls.push(`notice:${msg}`));
    expect(calls).toContain("tab:phmax");
    expect(calls).toContain("b1c:3");
    expect(calls).toContain("notice:ok");
  });

  it("apply odfiltruje neplatné psychRows z autosave", () => {
    const psychCalls: PsychRow[][] = [];
    const setters = {
      setTab: () => {},
      setMode: () => {},
      setBasicType: () => {},
      setBasic1Classes: () => {},
      setBasic1Pupils: () => {},
      setBasic2Classes: () => {},
      setBasic2Pupils: () => {},
      setIncl1Classes: () => {},
      setIncl1Pupils: () => {},
      setIncl2Classes: () => {},
      setIncl2Pupils: () => {},
      setPsychRows: (v: PsychRow[]) => psychCalls.push(v),
      setHealthRows: () => {},
      setExportLabel: () => {},
      setMinorityType: () => {},
      setMinority1Classes: () => {},
      setMinority1Pupils: () => {},
      setMinority2Classes: () => {},
      setMinority2Pupils: () => {},
      setGymRows: () => {},
      setMixedRows: () => {},
      setSpecial1Classes: () => {},
      setSpecial1Pupils: () => {},
      setSpecial2Classes: () => {},
      setSpecial2Pupils: () => {},
      setSpecialIIClasses: () => {},
      setSpecialIIPupils: () => {},
      setPrepClasses: () => {},
      setPrepChildren: () => {},
      setPrepSpecialClasses: () => {},
      setPrepSpecialChildren: () => {},
      setP38First: () => {},
      setP38Second: () => {},
      setP41First: () => {},
      setP41Second: () => {},
      setPhaRows: () => {},
      setPhpYear1: () => {},
      setPhpYear2: () => {},
      setPhpYear3: () => {},
      setPhpWizardStep: () => {},
      setPhpMethodMode: () => {},
      setPhpExcludedAbroad: () => {},
      setPhpExcludedForeignSchoolCz: () => {},
      setPhpExcludedIndividual: () => {},
      setPhpExcludedSchool: () => {},
      setSelectedExample: () => {},
      setWizardChoice: () => {},
      setZsWizardStep: () => {},
      setDataMode: () => {},
      setNv75Role: () => {},
      setNv75School: () => {},
      setNv75TeacherMin: () => {},
      setNv75TeacherMax: () => {},
      setMixedMethodFirstZsPupils: () => {},
      setMixedMethodFirstZsClasses: () => {},
      setMixedMethodFirstSpecialPupils: () => {},
      setMixedMethodFirstSpecialClasses: () => {},
      setMixedMethodSecondZsPupils: () => {},
      setMixedMethodSecondZsClasses: () => {},
      setMixedMethodSecondSpecialPupils: () => {},
      setMixedMethodSecondSpecialClasses: () => {},
    } as ZsFormSnapshotSetters;

    applyZsFormSnapshot(
      { psychRows: [{ kind: "psycholog", currentClasses: 1, currentPupils: 8 }] },
      setters,
      "ok",
      () => {},
    );
    expect(psychCalls.at(-1)).toEqual([]);
  });
});
