import type { CalculatorMode } from "./calculator-config";

export const DEFAULT_MODE: CalculatorMode = "phmax_full_zs_sec16";

export const DEFAULT_FORM_STATE = {
  mode: DEFAULT_MODE,
  view: "simple" as "simple" | "method",
  basicType: "full_more_than_2",
  basic1Classes: 10,
  basic1Pupils: 250,
  basic2Classes: 8,
  basic2Pupils: 225,
  sec16FirstClasses: 5,
  sec16FirstPupils: 40,
  sec16SecondClasses: 4,
  sec16SecondPupils: 32,
  dominantCFirstClasses: 0,
  dominantCFirstPupils: 0,
  dominantCSecondClasses: 0,
  dominantCSecondPupils: 0,
  dominantBFirstClasses: 0,
  dominantBFirstPupils: 0,
  dominantBSecondClasses: 0,
  dominantBSecondPupils: 0,
  minorityVariant: "minority1",
  minority1Classes: 0,
  minority1Pupils: 0,
  minority2Classes: 0,
  minority2Pupils: 0,
  prepClasses: 0,
  prepChildren: 0,
  prepSpecialClasses: 0,
  prepSpecialChildren: 0,
  p38First: 0,
  p38Second: 0,
  p41First: 0,
  p41Second: 0,
  phpYear1: 260,
  phpYear2: 272,
  phpYear3: 281,
  phpShortPeriod: false,
  phpExcludedSchool: false,
  teacherMode: "teacher_standard",
  headteacherMode: "head_first_stage",
  units: 0,
  otherStaffMode: "psychologist",
};